name: blogging

services:
  blogging-db:
    image: postgres:17.0-alpine3.20
    ports:
      - 6010:5432
    environment:
      - POSTGRES_USER=${POSS_USER}
      - POSTGRES_PASSWORD==${POSS_PASS}
    volumes:
      - blogging:/var/lib/postgres
volumes:
  blogging:
    external: false